[default]
# Dev mode
DEBUG = false
# Pathes
DB_PATH = 'data/db'
LOG_PATH = 'logs/bot.log'
PLAYER_ANALYSIS_PROMPT_PATH = 'prompts/player_analysis.txt'
# Internal parameters
DATETIME_FORMAT = '%Y-%m-%d %H:%M:%S'
TIMEZONE = 'US/Eastern'
# Logic parameters
ADMINS = [ '@PLACEHOLDER' ]
USERS = [ '@PLACEHOLDER' ]

[prod]
DEBUG = false
TOKEN = 'SECRET_PLACEHOLDER'
CONVERSATION_TIMEOUT = 86400            # 24 hours (in seconds)

[dev]
DEBUG = true
TOKEN = 'SECRET_PLACEHOLDER'
CONVERSATION_TIMEOUT = 60               # 1 minute (in seconds)
